//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<<< HEAD:PrimerEjercicioAJAX/PrimerEjercicioAJAX/Employee.cs
namespace PrimerEjercicioAJAX
========
namespace ComboMasTextBoxAJAX
>>>>>>>> 77c49f12752784c7b68e00faeed06661c045641d:ComboMasTextBoxAJAX/ComboMasTextBoxAJAX/Employees.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
<<<<<<<< HEAD:PrimerEjercicioAJAX/PrimerEjercicioAJAX/Employee.cs
            this.Employees1 = new HashSet<Employee>();
========
            this.Employees1 = new HashSet<Employees>();
            this.Orders = new HashSet<Orders>();
            this.Territories = new HashSet<Territories>();
>>>>>>>> 77c49f12752784c7b68e00faeed06661c045641d:ComboMasTextBoxAJAX/ComboMasTextBoxAJAX/Employees.cs
        }
    
        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Title { get; set; }
        public string TitleOfCourtesy { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string HomePhone { get; set; }
        public string Extension { get; set; }
        public byte[] Photo { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ReportsTo { get; set; }
        public string PhotoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
<<<<<<<< HEAD:PrimerEjercicioAJAX/PrimerEjercicioAJAX/Employee.cs
        public virtual ICollection<Employee> Employees1 { get; set; }
        public virtual Employee Employee1 { get; set; }
========
        public virtual ICollection<Employees> Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Territories> Territories { get; set; }
>>>>>>>> 77c49f12752784c7b68e00faeed06661c045641d:ComboMasTextBoxAJAX/ComboMasTextBoxAJAX/Employees.cs
    }
}
